- hosts: launched
  become: yes
  become_method: sudo

  tasks:
      - name: Update Repository
        apt_repository: repo="deb http://ftp.us.debian.org/debian wheezy-backports main" state=present

      - name: Install HAProxy
        apt: name=haproxy force=yes update_cache=yes

      - name: Copy HAProxy.cfg
        copy: src=templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg
