- hosts: launched
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "/Users/aakash.johari/.ssh/id_rsa"

  tasks:
  - name: update apt
    apt: update_cache=yes

  - name: install redis
    apt: pkg={{ item }} state=latest
    with_items:
        - redis-server

  - name: copy redis.conf file
    copy: src=templates/redis.conf dest=/etc/redis/redis.conf owner=redis

  - name: restart redis service
    service: name=redis-server state=restarted
