#! /bin/bash

### BEGIN INIT INFO
# Provides:          quaffle-frontend-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

PACKAGE="quaffle-frontend-service"
SERVICE=/etc/service/$PACKAGE

case $1 in
  start)
    echo "Starting service ..."
    svc -u $SERVICE
    sleep 60
    ;;
  stop)
    echo "Stopping service ..."
    svc -d $SERVICE
    ;;
  restart)
    echo "Stopping service ..."
    svc -d $SERVICE
    sleep 5

    echo "Starting service ..."
    svc -u $SERVICE
    sleep 60
    ;;
  status)
    svstat $SERVICE
    ;;
  shell)
    exec setuidgid $PACKAGE bash
    ;;
  *)
    echo "Usage $0 {start|stop|restart|status}"
    ;;
esac
